name: Osias

# Controls when the workflow will run
on:
  push:
  pull_request:
  workflow_dispatch:
  schedule:
    - cron:  '30 * * * *'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  Ubuntu-18-Deploy-OpenStack:
    runs-on: ubuntu-18.04
    strategy:
      fail-fast: false
      matrix:
        OPENSTACK_RELEASE: ["ussuri"]
    env:
      OPENSTACK_RELEASE: ${{ matrix.OPENSTACK_RELEASE }}
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.6
      - name: Install python dependencies
        run: |
          python -m pip install --upgrade pip
      - name: Deploy OpenStack Release [${{ env.OPENSTACK_RELEASE }}]
        run: |
          public_interface=$(route -n | awk '$1 == "0.0.0.0" {print $8}')
          MY_IP=$(ip -o -4 addr list "${public_interface}" | awk '{print $4}' | cut -d/ -f1)
          source all_in_one_openstack_deployment.sh ${{ env.OPENSTACK_RELEASE }} "$MY_IP"

  Ubuntu-20-Deploy-OpenStack:
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        OPENSTACK_RELEASE: ["victoria", "wallaby"]
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install python dependencies
        run: |
          python -m pip install --upgrade pip
      - name: Deploy OpenStack Release [${{ matrix.OPENSTACK_RELEASE }}]
        run: |
          public_interface=$(route -n | awk '$1 == "0.0.0.0" {print $8}')
          MY_IP=$(ip -o -4 addr list "${public_interface}" | awk '{print $4}' | cut -d/ -f1)
          source all_in_one_openstack_deployment.sh ${{ matrix.OPENSTACK_RELEASE }} "$MY_IP"
